### ISSUE TITLE
pdfs with extremely large pages

### ISSUE THREAD

**Issue by smsaladi** [smsaladi/jetfighter#5]
these should be handled better. Both during the calculation phase as well as while generating previews

Probably could just skip over them -- although presumably these pages actually have figures... 

Traceback (most recent call last):
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/flask_rq2/job.py", line 41, in perform
    return super(FlaskJob, self).perform()
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/saladi/github/jetfighter/webapp.py", line 408, in process_paper
    obj.pages, obj.parse_data = detect_rainbow_from_file(fn)
  File "/home/saladi/github/jetfighter/detect_cmap.py", line 214, in detect_rainbow_from_file
    df = pd.concat([parse_img(p) for p in convert_to_img(fn)],
  File "/home/saladi/github/jetfighter/detect_cmap.py", line 214, in <listcomp>
    df = pd.concat([parse_img(p) for p in convert_to_img(fn)],
  File "/home/saladi/github/jetfighter/detect_cmap.py", line 64, in parse_img
    im = skimage.io.imread(fn)
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/skimage/io/_io.py", line 62, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 214, in call_plugin
    return func(*args, **kwargs)
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/skimage/io/_plugins/pil_plugin.py", line 36, in imread
    im = Image.open(f)
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/PIL/Image.py", line 2609, in open
    im = _open_core(fp, filename, prefix)
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/PIL/Image.py", line 2600, in _open_core
    _decompression_bomb_check(im.size)
  File "/home/saladi/anaconda3/envs/jet/lib/python3.6/site-packages/PIL/Image.py", line 2539, in _decompression_bomb_check
    (pixels, 2 * MAX_IMAGE_PIXELS))
PIL.Image.DecompressionBombError: Image size (179090472 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

**Comment by smsaladi** [comment]
for a sense of scale, there were 5 in 6000

**Comment by smsaladi** [comment]
no longer relevant -- handled by iiif server (see #3)
